export const BASE_URL = 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_288,h_360/'
export const HOME_API = 'https://www.swiggy.com/dapi/restaurants/list/v5?lat=latitude&lng=longitude&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING'
export const RESTURANT_DETAIL = 'https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=latitude&lng=longitude&restaurantId=REST_ID'
export const UPDATE = 'https://www.swiggy.com/dapi/restaurants/list/update'
export const SEARCHLOCATION='https://www.swiggy.com/dapi/misc/place-autocomplete?input=INPUT_DATA&types='
export const ADDRESSLATLONG = 'https://nominatim.openstreetmap.org/search?q=ADDRESS_DATA&format=json&addressdetails=1'